version: "3"

include:
  - ../compose-common.yml

volumes:
  silverbullet-vol:
    external: true

services:
  silverbullet:
    image: "zefhemel/silverbullet:0.5.10"
    container_name: "silverbullet"
    networks:
      - proxy-net
    restart: unless-stopped
    volumes:
      - silverbullet-vol:/space
